//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWD2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Category
    {
        public Product_Category()
        {
            this.Products = new HashSet<Product>();
            this.Product_Category1 = new HashSet<Product_Category>();
            this.PurchasedOrders = new HashSet<PurchasedOrder>();
        }
    
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> UpperCategory { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product_Category> Product_Category1 { get; set; }
        public virtual Product_Category Product_Category2 { get; set; }
        public virtual ICollection<PurchasedOrder> PurchasedOrders { get; set; }
    }
}
