//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWD2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Image = new HashSet<Product_Image>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Product_Image> Product_Image { get; set; }
        public virtual Product_Category Product_Category { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
