//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWD2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedOrder
    {
        public PurchasedOrder()
        {
            this.PurchasedOrder_Image = new HashSet<PurchasedOrder_Image>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OrderStatus { get; set; }
        public string Address { get; set; }
        public double Total { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Product_Category Product_Category { get; set; }
        public virtual ICollection<PurchasedOrder_Image> PurchasedOrder_Image { get; set; }
    }
}
