//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWD2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public int Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Status Product_Status { get; set; }
    }
}
