//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWD2015.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9DFD26_SWD2015Entities : DbContext
    {
        public DB_9DFD26_SWD2015Entities()
            : base("name=DB_9DFD26_SWD2015Entities")
        {
            Configuration.LazyLoadingEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Order_Status> Order_Status { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Product_Category> Product_Category { get; set; }
        public DbSet<Product_Image> Product_Image { get; set; }
        public DbSet<Product_Status> Product_Status { get; set; }
        public DbSet<PurchasedOrder> PurchasedOrders { get; set; }
        public DbSet<SoldOrder> SoldOrders { get; set; }
        public DbSet<Stock> Stocks { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
